//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWSReadPart
    {
        public System.Guid UN { get; set; }
        public string ReadPart { get; set; }
        public Nullable<System.Guid> ListUN { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public string ReadPartHtml { get; set; }
    
        public virtual EWSList EWSList { get; set; }
        public virtual EWSUser EWSUser { get; set; }
        public virtual EWSReadingPartCategory EWSReadingPartCategory { get; set; }
    }
}
